### ISSUE TITLE
Set IP's manually

### ISSUE THREAD

**Issue by DuckY1987** [lazcad/homeassistant#13]
Hi there,

as it-specialist i have a bigger setup at home with multiple networks, subnets and ssids.

As this component only includes multicast discover i can not see my gateway located in another subnet :-(.

Isolated SSIDs and network traffic with a layer 7 firewall.

Additionally i would like to setup a gateway via IPSec VPN, its not possible too.

Is it possible to include a manual ip configuration in this component?

Thanks.

**Comment by monster1025** [comment]
Xiaomi gateway responds to a multicast group, not to one(server) ip.

**Comment by DuckY1987** [comment]
So its caused by design of the gateway not the component? :-(

I don't know why everybody expect that everything is always on the same network :-(.

**Comment by tam-wh** [comment]
It is possible to have manual ip configuration but like @monster1025 said, you'll still need to be able to process multicast message in order to receive updates pushed from the gateway.

**Comment by DuckY1987** [comment]
okay, thats sad :-(.

I reconfigured my whole setup, right now same wifi (ssid), i have a multiple interface configuration on my pi (wired & wifi) .... and the xiaomi didn't get discovered.

I can see with my multicast tester that the xiaomi gateway sends frequently heartbeats, but somehow my hass doesn't see the gateway itself.

How can i verify that it is not a socket issue?

i used all configuration possibilities mentioned in the readme, with sid, with interface etc.

Here a couple details to my setup:

PI3 as hass hardware latest updates, latest hass.

pycrypto and pysocks are installed 

eth0 and wlan0 (power_safe:off)

Xiaomi: Version 2.19  / Latest firmware.

Dev mod on: password set.

xiaomi:
  gateways:
    - sid: lowercasemacaddresswithout:
      key: password
  interface: same_as_wlan_interface_IP

Tested multicast responds with android multicast tester app 224.0.0.50 9898

Message in HASS: no gateway discovered

Is there a test script to verify that isn't a socket binding issue?

Or some other suggestions? :-(

some ideas, i debugged already 5h what could cause the issues.

**Comment by tam-wh** [comment]
Remove the interface option. There's no need to put that in unless you have issue with binding the socket

**Comment by DuckY1987** [comment]
As mentioned i tried it with and without it doesn't work for me either way.

**Comment by DuckY1987** [comment]
YEAH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! you fixed my issues. @ravetam with your pullrequest! Thanks dude.

**Comment by tam-wh** [comment]
Good to hear
