### ISSUE TITLE
Aqara switch

### ISSUE THREAD

**Issue by joaoasilva** [lazcad/homeassistant#21]
Aqara switches should be as the light switches, instead when you click on it on the interface it turns on and then off automatically on the interface but stays on on the physical switch.
I've made a dirty fix on the switch code:

>     def turn_on(self, **kwargs):
>         """Turn the switch on."""
>         if self._data_key == 'status':
>             if self.xiaomi_hub.write_to_hub(self._sid, self._data_key, 'on'):
>                 self._state = True
>         else:
>             if self._state:
>                 self.turn_off()
>             else:
>                 if self.xiaomi_hub.write_to_hub(self._sid, self._data_key, 'on'):
>                     self._state = True

But this isn't the solution as they need to behave as a light switch and not toggle automatically on the interface.

Regards,

**Comment by joaoasilva** [comment]
Further investigation and it seems that 'ctrl_neutral1', 'ctrl_neutral2' should be binary_sensors and not switches.

Regards

**Comment by joaoasilva** [comment]
>     def turn_on(self, **kwargs):
>         """Turn the switch on."""
>         if self._data_key == 'status':
>             if self.xiaomi_hub.write_to_hub(self._sid, self._data_key, 'on'):
>                 self._state = True
>         else:
>             if self._state:
>                 self.turn_off()
>             else:
>                 if self.xiaomi_hub.write_to_hub(self._sid, self._data_key, 'on'):
>                     self._state = True
> 	
>     def turn_off(self):
>         """Turn the switch off."""
>         if self._data_key == 'status':
>             if self.xiaomi_hub.write_to_hub(self._sid, self._data_key, 'off'):
>                 self._state = False
>         else:
>             if not self._state:
>                 self.turn_on()
>             else:
>                 if self.xiaomi_hub.write_to_hub(self._sid, self._data_key, 'off'):
>                     self._state = False
>             
>     def parse_data(self, data):
>         value = data.get(self._data_key)
>         if value is None:
>             return False
>             
>         if self._state:
>             ztate = 'True'
>         else:
>             ztate = 'False'
> 
>         _LOGGER.error('value:' + value + ' state:' + ztate)
>         state = value == 'on'
>         if self._data_key == 'status':
>             if self._state == state:
>                 return False
>             else:
>                 self._state = state
>                 return True
>         else:
>             if state:
>                 return True
>             else:
>                 return False

This is the maximum I could go... I never worked with python or know anything about the HA framework so I'm totally blind here.
With that at least it works but the icon colour only changes to the right state the first time I click on it, afterwards it doesn't turn off when I click on the switch again but the physical switch at least it works.
If someone with more experience can spot what's missing I would appreciate.

Thanks.

Regards,

**Comment by tam-wh** [comment]
I'll check the latest code and see if something breaks. The old code I'm using works fine

**Comment by Danielhiversen** [comment]
@joaoasilva Why do you have a call to turn_off in the turn_on function?
When should a turn_on call turn the switch off?

**Comment by Danielhiversen** [comment]
@joaoasilva Could you try this fix: https://github.com/lazcad/homeassistant/pull/22/files

**Comment by joaoasilva** [comment]
Ahahaha, this was my first experience with Python and HA, as I said was a dirty hack just to make it work, not a solution.
I can confirm your fix works!
Thanks!
