### ISSUE TITLE
Handle newly connected devices without restart

### ISSUE THREAD

**Issue by rytilahti** [lazcad/homeassistant#23]
I just added a new temp&humidity sensor through the app to the system which isn't being detected by the homeassistant automatically. Here the relevant part of the log:
17-02-12 19:06:34 DEBUG (Thread-13) [custom_components.xiaomi] MCAST (heartbeat) << {'sid': '158d0001XXXXXX', 'model': 'sensor_ht', 'short_id': 36438, 'data': '{"temperature":"10000","humidity":"0"}', 'cmd': 'heartbeat'}
17-02-12 19:06:35 DEBUG (Thread-13) [custom_components.xiaomi] MCAST (report) << {'sid': '158d0001XXXXXX', 'model': 'sensor_ht', 'short_id': 36438, 'data': '{"temperature":"2474"}', 'cmd': 'report'}

Just an idea, maybe it would make sense to add non-existing sensors based on the heartbeat?

**Comment by tam-wh** [comment]
It is entirely possible to add a new unrecognized device based on heartbeat. In fact i got it implemented on my own iot framework. I'll try and see if it works in HA

**Comment by DuckY1987** [comment]
Probably you can have a look on the mysensors component it does it already with new discovered nodes that you don't need to invent the wheel once more ;-).

**Comment by DuckY1987** [comment]
To the ghost openings: they seems to be disappeared, everything works as expected. i have now 6 door sensor up and running 3 more are not installed yet...The log is eating up my disk space in the hope next time I will see more.
