### ISSUE TITLE
Error- struct.error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by covrig** [lazcad/homeassistant#24]
Hello I am using the latest version and I am receiving the error below. This shows up in the log once every 10s to couple of minutes. After some time it crashes the gateway.
This wasn't the case in the past.
Any suggestions?
Thank you.
```
17-02-14 20:36:19 ERROR (Thread-10) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi.py", line 363, in push_data
    device.push_data(jdata)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi.py", line 417, in push_data
    if self.parse_data(data):
  File "/home/homeassistant/.homeassistant/custom_components/light/xiaomi.py", line 65, in parse_data
    rgba = struct.unpack('BBBB', rgbhex)
struct.error: unpack requires a bytes object of length 4
```

**Comment by tam-wh** [comment]
Try turn on debugging and see what data is being pushed from the gateway

**Comment by covrig** [comment]
@ravetam I turned on debugging but I am seeing something really weird. The error does not show in debugging mode but it displays in normal mode. I get the error randomly, more than 50 times per day.

I am also experiencing something abnormal. After a 1-2 days, the Xiaomi gateway responds only to HASS but loses connection with the MiHome app. Any automation set from the MiHome app does not work anymore. Some MiHome automations do not work at all if the hub is linked to HASS. If the HASS is off everything works properly.

**Comment by tam-wh** [comment]
Can you try the latest commit?
