### ISSUE TITLE
Switch can't respond to my operation

### ISSUE THREAD

**Issue by Guoer-xz** [lazcad/homeassistant#29]
Very good plug-in, sensor, socket, lamps are stable and reliable work, but I switch both the wifi86 and the button are able to properly do automatic recognition, but not in response to my operation on the physical keys, but in the automatic page interface click on the Tigger the operation performed, what else can I do the investigation, thank you
######## 网 关 #############
#小米网关#
xiaomi:
 gateways:
   - sid: xxxxxxxxxxx
     key: xxxxxxxxxxxxxx

###################################################
###################################################
# 动 作 #
automation:
- alias: Dining wall switch left click
  trigger:
    platform: event
    event_type: click
    event_data:
        entity_id: binary_sensor.wall_switch_left_158d00013e6962
        chick_type: single
  action:
    service: switch.toggle
    entity_id: switch.plug_158d0000f87aa4

**Comment by tam-wh** [comment]
Typo? 

chick_type: single

Should be

click_type: single

**Comment by Guoer-xz** [comment]
Thanks, I was so careless, but I still can't use the switch after the change. What else can I suggest?

**Comment by tam-wh** [comment]
What's in the error log?

**Comment by Guoer-xz** [comment]
Thank you, after the change has a key to work, my mistake, the other I continue to investigate
