### ISSUE TITLE
What is the key?

### ISSUE THREAD

**Issue by mp3llll** [lazcad/homeassistant#30]
The mac of the device? password ?

Thanks!

MP

**Comment by mp3llll** [comment]
OK find what is, how do i make a screen for Motion Sensors and door sensor?

here how my.. all All messy
![xaiomoi](https://cloud.githubusercontent.com/assets/24222210/23522900/64b0e67a-ff8d-11e6-8b92-1620748c1109.png)

**Comment by tam-wh** [comment]
Readme has the steps to get the key. And to configure the yaml file, you can get more help in the forum or read HA help file because that's related to HomeAssistant, not this component.
