### ISSUE TITLE
Light RGB data error and Gateway losing connection

### ISSUE THREAD

**Issue by covrig** [lazcad/homeassistant#31]
Hello.
I am facing some issues with my HASS (0.39.1) installation and the Xiaomi component. I also need to mention that I am using the official HASS Yeelight component. Maybe there is an interconnection.

1. See the error log below. It seems something weird is happening with the hex conversion or something. Not critical.
2. The second problem I am facing is the Xiaomi gateway losing connection to the Mi Home app. The button functions and the automations set within the Mi Home app don't work anymore. **However, it still sends data to HASS.** After a 2-3 days the gateway fails completely and I need to reset it (unplug it and restart HASS).

**A question.** 
Is it OK if I change the Mi Home server from China Mainland to Singapore (International)? Is the component affected in any way?

```17-03-06 18:33:44 ERROR (Thread-11) [custom_components.light.xiaomi] Light RGB data error. Must be 8 characters. Received: fdfe18
17-03-06 18:33:45 ERROR (Thread-4) [custom_components.light.xiaomi] Light RGB data error. Must be 8 characters. Received: fe00
17-03-06 18:33:46 ERROR (Thread-4) [custom_components.light.xiaomi] Light RGB data error. Must be 8 characters. Received: 1d5fc
17-03-06 18:34:52 ERROR (Thread-7) [custom_components.light.xiaomi] Light RGB data error. Must be 8 characters. Received: 900fa
17-03-06 18:34:53 ERROR (Thread-10) [custom_components.light.xiaomi] Light RGB data error. Must be 8 characters. Received: fb03fa
17-03-06 18:34:54 ERROR (Thread-6) [custom_components.light.xiaomi] Light RGB data error. Must be 8 characters. Received: ffffff
```

**Comment by tam-wh** [comment]
Did you get that error when you control the light using MiHome app or using HA?

**Comment by tam-wh** [comment]
No, changing the server doesn't affect the component at all

**Comment by covrig** [comment]
The error is random. I didn't try to control the light.

**Comment by aferraz** [comment]
Hi,
 same error in my installation logs, but I have not noticed a problem while using.

Regards
 Alessandro

**Comment by tam-wh** [comment]
I got that error but I'm not really sure why those are being sent from the gateway. Anyway, I'll make those a normal debug log instead of an error in the next commit
