### ISSUE TITLE
TTS and Battery Level

### ISSUE THREAD

**Issue by FlipUberFlop** [lazcad/homeassistant#33]
Hi there,

Thanks for the awesome work on the component. Its working really well! 
Just wanted to know if its possible to push audio to the gateway to use a service such as Google TTS?
Another thing, do the sensors have a battery level component? Would it be tricky to implement? It would be helluva handy to have this feature...

Thanks man and keep up the great work!

**Comment by abmantis** [comment]
Regarding battery, it is supported on the newer 1.4.1_144 firmware (which, I think, is not yet publicly released). I've finished support for it on PR #32, but you will only see any data on HA once you have that firmware version.

**Comment by FlipUberFlop** [comment]
Aaah, brilliant! Thanks for the feedback
