### ISSUE TITLE
Cannot read property 'v' of undefined

### ISSUE THREAD

**Issue by sofixa** [lazcad/homeassistant#35]
I get "Cannot read property 'v' of undefined" in the HASS web interface on a door/window, motion sensor and switch(but not on the temperature/humidity sensor). 

What could that be? Maybe battery level? Anyone have any ideas?

**Comment by tam-wh** [comment]
Are you using the latest commit?

**Comment by ghost** [comment]
Hi, same issue here.

downloaded just now and it says that in the web interface. Log file looks good, I can see every click or motion detection.

**Comment by sofixa** [comment]
Running the latest commit the error is no longer there, seems to be working fine.
