### ISSUE TITLE
Can you put this component to the official web site?

### ISSUE THREAD

**Issue by crhan** [lazcad/homeassistant#52]

**Comment by palitu** [comment]
I agree - it would be great to have it straight out of the box!.

hell - there is a beer in it for ya!

**Comment by crhan** [comment]
If I have some time to do this, I hope you don't mind

**Comment by jcastro** [comment]
+1!

**Comment by acrueda** [comment]
Yesssss

**Comment by crhan** [comment]
https://github.com/home-assistant/home-assistant/pull/8555 merged.
