### ISSUE TITLE
Can this component be used with HASS.IO?

### ISSUE THREAD

**Issue by dobrynski** [lazcad/homeassistant#61]
I followed the instructions but it's not finding the gateway:
```
2017-06-21 11:50:26 ERROR (SyncWorker_1) [custom_components.xiaomi] No gateway discovered
2017-06-21 11:50:26 ERROR (MainThread) [homeassistant.setup] Setup failed for xiaomi: Component failed to initialize.
```
I've tried setting the interface manually to the one on the same subnet as the gateway but it didn't help (I don't know what it auto-chooses).

Any help would be greatly appreciated.

Regards,
Michal

**Comment by dobrynski** [comment]
The answer is.. Yes it can!

**Comment by andreipopovici** [comment]
Hi @mihalski, it would be awesome if you could post how you got this to work. I'm getting the same error and tried the same thing (the `interface` option).

**Comment by dobrynski** [comment]
@andreipopovici Your problem is most likely that the gateway isn't really in dev mode. Make sure your app is set to Mainland China, that you update the firmware of the Xiaomi gateway, and that you enable dev mode and grab the key. The key is uppercase if displayed so in the app (mine was).

The key was setting the app to Mainland China and then following the process.

**Comment by andreipopovici** [comment]
For everyone else reaching this, what worked for @mihalski and me was activating developer mode and restarting the gateway, as well as using the `interface` option with the gateway's IP address.

You can find updated (as of today) instructions here: https://github.com/fooxy/homeassistant-aqara/wiki/Enable-dev-mode

**Comment by dobrynski** [comment]
Note that in my case those instructions did NOT work UNTIL I switched from United States to Mainland China upon which time the firmware could be updated to a newer version.
