### ISSUE TITLE
Wall switches are not updating in UI

### ISSUE THREAD

**Issue by emilhetty** [lazcad/homeassistant#64]
I have several Wall switches, both single and double, they all are not updating in the UI when pressed.
The logs shows that they are pressed:
![image](https://user-images.githubusercontent.com/7728206/27456353-0b9c0300-57a1-11e7-910c-10cc48f34301.png)

This is the UI, capture some seconds after:
![image](https://user-images.githubusercontent.com/7728206/27456426-4a0c8b1e-57a1-11e7-957f-3c3124ba5e83.png)

**Comment by jcastro** [comment]
Use Daniel fork they work for me!

**Comment by emilhetty** [comment]
Could you post a link to it? Couldn't find it.
Found that this issue is not just for the wall switches, but for all switches that is unnamed. The only switches I have that are updating in UI is the ones that I have gave name to.

**Comment by emilhetty** [comment]
Found it :)
